# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# Update import to use your new structure
from app.ui.pages import (
    DashboardPage,
    InventoryPage,
    ReportsPage,
    CustomersPage,
    SuppliersPage,
    SalesPage,
    MaintenancePage,
    HelpPage,
    AboutPage
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Set up the main window properties
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        
        # Create the central widget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Set up the main layout
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        
        # Create the sidebar
        self.create_sidebar()
        
        # Create the stacked widget for pages
        self.stackedWidgetMain = QtWidgets.QStackedWidget()
        self.main_layout.addWidget(self.stackedWidgetMain)
        
        # Add all pages to the stacked widget
        self.add_pages()
        
        # Connect sidebar buttons to page switching
        self.connect_buttons()
        
        # Set initial page
        self.stackedWidgetMain.setCurrentIndex(0)
        
    def create_sidebar(self):
        # Create the sidebar widget
        self.sidebar = QtWidgets.QWidget()
        self.sidebar.setFixedWidth(240)
        self.sidebar.setStyleSheet("background-color: #232323;")
        
        # Logo
        self.logo_label = QtWidgets.QLabel(self.sidebar)
        self.logo_label.setGeometry(QtCore.QRect(10, 20, 221, 101))
        self.logo_label.setPixmap(QtGui.QPixmap("app/resources/images/Miere1.png"))
        
        # Navigation buttons container
        self.nav_container = QtWidgets.QWidget(self.sidebar)
        self.nav_container.setGeometry(QtCore.QRect(30, 130, 181, 394))
        
        # Navigation layout
        self.nav_layout = QtWidgets.QVBoxLayout(self.nav_container)
        self.nav_layout.setContentsMargins(0, 0, 0, 0)
        
        # Create navigation buttons
        self.create_nav_button("Dashboard", "app/resources/images/Home.png")
        self.create_nav_button("Inventory", "app/resources/images/Inventory.png")
        self.create_nav_button("Reports", "app/resources/images/Group 11.png")
        self.create_nav_button("Customers", "app/resources/images/Suppliers.png")
        self.create_nav_button("Suppliers", "app/resources/images/Suppliers.png")
        self.create_nav_button("Sales", "app/resources/images/Order.png")
        self.create_nav_button("Maintenance", "app/resources/images/Group 15.png")
        
        # Bottom buttons container
        self.bottom_container = QtWidgets.QWidget(self.sidebar)
        self.bottom_container.setGeometry(QtCore.QRect(20, 560, 201, 141))
        
        # Bottom buttons layout
        self.bottom_layout = QtWidgets.QVBoxLayout(self.bottom_container)
        self.bottom_layout.setContentsMargins(0, 0, 0, 0)
        
        # Create bottom buttons
        self.create_bottom_button("Help", "app/resources/images/Settings.png")
        self.create_bottom_button("About", "app/resources/images/Suppliers.png")
        self.create_bottom_button("Logout", "app/resources/images/Vector.png")
        
        # Add sidebar to main layout
        self.main_layout.addWidget(self.sidebar)
        
    def create_nav_button(self, text, icon_path):
        button = QtWidgets.QPushButton(f" {text}")
        button.setMinimumHeight(50)
        button.setFont(QtGui.QFont("Segoe UI", 10))
        button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        button.setStyleSheet(
            "color: white; "
            "text-align: left; "
            "padding-left: 5px;"
        )
        button.setIcon(QtGui.QIcon(icon_path))
        
        # Store the button reference with its name
        button_name = f"pushButton{text}"
        setattr(self, button_name, button)
        
        self.nav_layout.addWidget(button)
        
    def create_bottom_button(self, text, icon_path):
        button = QtWidgets.QPushButton(f" {text}")
        button.setMinimumHeight(40)
        button.setFont(QtGui.QFont("Segoe UI", 8))
        button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        button.setStyleSheet(
            "color: white; "
            "text-align: left; "
            "padding-left: 5px;"
        )
        button.setIcon(QtGui.QIcon(icon_path))
        button.setIconSize(QtCore.QSize(18, 18))
        
        # Store the button reference with its name
        button_name = f"pushButton{text}"
        setattr(self, button_name, button)
        
        self.bottom_layout.addWidget(button)
        
    def add_pages(self):
        # Dashboard page
        dashboard_page = DashboardPage()
        self.stackedWidgetMain.addWidget(dashboard_page)
        
        # Inventory page
        inventory_page = InventoryPage()
        self.stackedWidgetMain.addWidget(inventory_page)
        
        # Reports page
        reports_page = ReportsPage()
        self.stackedWidgetMain.addWidget(reports_page)
        
        # Customers page
        customers_page = CustomersPage()
        self.stackedWidgetMain.addWidget(customers_page)
        
        # Suppliers page
        suppliers_page = SuppliersPage()
        self.stackedWidgetMain.addWidget(suppliers_page)
        
        # Sales page
        sales_page = SalesPage()
        self.stackedWidgetMain.addWidget(sales_page)
        
        # Maintenance page
        maintenance_page = MaintenancePage()
        self.stackedWidgetMain.addWidget(maintenance_page)
        
        # Help page
        help_page = HelpPage()
        self.stackedWidgetMain.addWidget(help_page)
        
        # About page
        about_page = AboutPage()
        self.stackedWidgetMain.addWidget(about_page)
        
    def connect_buttons(self):
        # Connect main navigation buttons to page switching
        self.pushButtonDashboard.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(0))
        self.pushButtonInventory.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(1))
        self.pushButtonReports.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(2))
        self.pushButtonCustomers.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(3))
        self.pushButtonSuppliers.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(4))
        self.pushButtonSales.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(5))
        self.pushButtonMaintenance.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(6))
        self.pushButtonHelp.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(7))
        self.pushButtonAbout.clicked.connect(lambda: self.stackedWidgetMain.setCurrentIndex(8))
        # Logout button would typically handle logout functionality, not switch pages


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
